  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 # Optional
      # - PLEX_CLAIM= # Optional - Obtain from https://www.plex.tv/claim/
    volumes:
      - ./volumes/plex/library:/config
      - ./volumes/plex/transcode:/transcode
      - ./ssl:/ssl
      - ./media/tvshows:/media/tv
      - ./media/movies:/media/movies
      - ./media/animation:/media/animation
      - ./media/music:/media/music
    devices:
      - /dev/dri:/dev/dri # Optional: for hardware transcoding
    restart: unless-stopped
